### PR TITLE
Rephrase documentation for fallbackSelection.

### PR DESCRIPTION
**Pull request by palli**
The motivation here is a typo in the paragraph (attrForSelected), but also rephrase it a little bit
as an attempt to make it clearer.

### CODE REVIEW

**Comment by palli** [comment]
I signed it!

**Comment by TimvdLippe** [comment]
Thanks, is a lot clearer indeed!

**Comment by bicknellr** [comment]
Thanks!

**Comment by palli** [comment]
Thanks for mergin (one extra reply to get cla:yes)

**Pull request merged**
