### PR TITLE
Keep current selection when attrForSelected is reset 

### LINKED ISSUE #162: dashToCamelCase fails when attrForSelected is null
This can happen for cases like the following one
```html
<iron-selector id="selector" selected="value0" attr-for-selected="some-attr">
  <div some-attr="value0">Item 0</div>
  <div some-attr="value1">Item 1</div>
</iron-selector>
<script>
  setTimeout(function() {
     selector.attrForSelected = null;
  }, 1000);
</script>
```
Resetting `attr-for-selected` should not fail in this case, and probably keep the current selection.

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #162

### CODE REVIEW

**Comment by bicknellr** [comment]
I think #161 made more sense for fixing this; changing `attrForSelected` (even to null, for example) seems like it should also change the selection.

**Comment by valdrinkoshi** [comment]
@bicknellr with the last commit now we also update the `selected` value in order to preserve the current selection.

**Comment by bicknellr** [comment]
(responding to self comment above) @valdrinkoshi pointed out that I wasn't correct in my assumption about how this was supposed to work, so we're moving back to this PR, with changes for a particular edge case (changing `attrForSelected` to something falsy).

**Comment by bicknellr** [comment]
Once the tests pass, LGTM!

**Comment by valdrinkoshi** [comment]
Merging this, opened an issue to revert to use polymer-cli here https://github.com/PolymerElements/iron-selector/issues/164

**Pull request merged**
