### PR TITLE
behavior doc update

### PR DESCRIPTION
**Pull request by atotic**
Behavior docs get visible with these changes.

### CODE REVIEW

**Comment by cdata** [comment]
LGTM :+1:

**Comment by cdata** [comment]
Actually, I had to revoke my LGTM.

Can you try making the comment an HTML comment, but placing it immediately _after_ the `<link>` tags in the page? I think the problem is that it has to appear before the script tag, not that it has to be inside the script.

**Comment by atotic** [comment]
They do not show up that way.

**Comment by atotic** [comment]
HTML comments only work with dom-module

**Pull request merged**
