### PR TITLE
issue #25

### PR DESCRIPTION
**Pull request by wilbiga**

### CODE REVIEW

**Comment by samccone** [comment]
The current syntax is fine, unless there was a reason why we needed an explicit null default.

:xref: https://github.com/PolymerElements/iron-selector/issues/25#issuecomment-113642082

I think that we can close this.

**Comment by wilbiga** [comment]
I known the syntax is fine. I was trying to use this element on a table to select the child tr element and without the "value:null" there was an error. Adding this piece of code it start working properly.

At the moment i can't find the example to reproduce this issue.

**Comment by wilbiga** [comment]
i didn't find the original code and i tried to replicate the problem but now is working. Probably i had some other problem or it got fixed somewhere else.

**Comment by samccone** [comment]
:+1: sgtm

**Pull request closed without merging**
