### PR TITLE
Allows selected to be set using index, even if attr-for-selected is used

### LINKED ISSUE #87: Can't select index when using attr-for-selected
Firstly, I understand and acknowledge that it is **by design** that if *attr-for-selected* is not null then the selected property is no longer the index and becomes the *attr-for-selected* variable.

Now, I came across this issue when using the *paper-tabs* element and the *attr-for-selected property*.

The context:
````
<paper-tabs id="tabs" selected="{{selected}}" attr-for-selected="someObject">
    <template is="dom-repeat" items="{{AjaxData.data}}">
        <paper-tab someObject$="{{item}}">{{item.name}}</paper-tab>
    </template>
</paper-tabs>
````
Where AjaxData would be something like:
````
{
  "data": [
    {
      "name": "Foo",
      "image_url": "/images/foo.png"
    },
    {
      "name": "Bar",
      "image_url": "/images/bar.png"
    }
}
```

I use the dictionary like object in the *attr-for-selected* as it can then be used in js to do some cool stuff:
```
var tabs = document.querySelector('#tabs');
tabs.addEventListener('iron-activate', function(e) {
    console.log(e.detail.selected);
    var jsonData = JSON.parse(e.detail.selected);
    var url = jsonData['image_url'];
    // Now we can set some ajax.url = url
}
```

Here is where the problem starts, I am using page.js to do client side routing - every time the user selects the page which has the paper-tabs, I would like the tabs to be 'reset' and the first tab to be selected.

One can no longer use `.selected=0` **and** no knowledge is known of what the *attr-for-selected* is for the first (dynamically inserted) element.

It would be really useful to have a **selectIndex(value)** function (like the `selectNext()` and `selectPrevious()` functions). This function could just use the *_indexToValue(index)* to get the corresponding value for the given index (so that *attr-for-selected* will keep `.selected` happy). This solves the problem of someone still needing to address an index while using the *attr-for-selected* property.

### PR DESCRIPTION
**Pull request by graeme44**
This closes #87.

### CODE REVIEW

**Comment by graeme44** [comment]
I signed it!

**Comment by bicknellr** [comment]
Thanks for the PR! This needs to be implemented in `IronMultiSelectableBehavior` + tested.

**Comment by bicknellr** [comment]
.. also rebased apparently? Weird for such a self-contained PR.

**Comment by bicknellr** [comment]
@graeme44, you there? Just wanted to give you a heads up that I'm going take over adding this feature soon - probably before the end of the week. If you'd prefer to keep maintaining this PR, please leave a comment.

**Comment by graeme44** [comment]
@bicknellr, that sounds good! I'm happy for you to take over.

**Comment by bicknellr** [comment]
Ok, I just created a new branch, issue-87, pointing to the same commit as current master. Could you change the base branch for this PR to that so that I can pull your commits into it?

**Comment by graeme44** [comment]
@bicknellr, Rebase done.

**Comment by bicknellr** [comment]
@graeme44, just one more step: could you open a new PR with 'issue-87' as the base branch? I thought there was a way to change this on an open a PR but some quick searching seems to imply otherwise. :/

**Comment by bicknellr** [comment]
Oh, forgot to close this after merging #110.

**Pull request closed without merging**
